#!/usr/bin/env python3
"""
Visualize RIV (Rotation-Invariant View) images generated by generate_riv_images.py

This script loads and displays the 3-channel panoramic images:
  - Channel 0: Reflectivity
  - Channel 1: Range
  - Channel 2: Normal Intensity

Usage:
    python visualize_riv_images.py <path_to_npy_file>
    python visualize_riv_images.py <path_to_npy_file> --channel <0|1|2|all>
    python visualize_riv_images.py <path_to_npy_file> --save <output_path.png>
"""

import numpy as np
import cv2
import argparse
import os
import sys
import matplotlib.pyplot as plt
from pathlib import Path


def load_riv_image(npy_path):
    """
    Load a RIV image from .npy file.

    Args:
        npy_path: Path to the .npy file

    Returns:
        image: (H, W, 3) float32 array with values in [0, 255]
    """
    if not os.path.exists(npy_path):
        raise FileNotFoundError(f"File not found: {npy_path}")

    image = np.load(npy_path)

    if image.ndim != 3 or image.shape[2] != 3:
        raise ValueError(f"Expected 3-channel image (H,W,3), got shape {image.shape}")

    return image.astype(np.float32)


def normalize_for_display(channel):
    """
    Normalize a single channel to [0, 255] for display.

    Args:
        channel: (H, W) float32 array

    Returns:
        normalized: (H, W) uint8 array
    """
    # Clip to valid range
    channel = np.clip(channel, 0, 255)
    return channel.astype(np.uint8)


def visualize_channels(image, channel_idx=None, save_path=None, show=True):
    """
    Visualize RIV image channels.

    Args:
        image: (H, W, 3) float32 array
        channel_idx: None for all channels, or 0/1/2 for specific channel
        save_path: Optional path to save the visualization
        show: Whether to display the image using matplotlib
    """
    channel_names = ['Reflectivity', 'Range', 'Normal Intensity']

    if channel_idx is None:
        # Display all three channels
        fig, axes = plt.subplots(2, 2, figsize=(15, 8))
        fig.suptitle('RIV Image Visualization', fontsize=16, fontweight='bold')

        # Individual channels
        for i in range(3):
            row, col = (i // 2, i % 2)
            channel = normalize_for_display(image[:, :, i])
            axes[row, col].imshow(channel, cmap='viridis', aspect='auto')
            axes[row, col].set_title(f'Channel {i}: {channel_names[i]}')
            axes[row, col].axis('off')

            # Add colorbar
            im = axes[row, col].images[0]
            plt.colorbar(im, ax=axes[row, col], fraction=0.046, pad=0.04)

        # RGB composite (for visualization purposes)
        rgb_composite = np.zeros_like(image)
        for i in range(3):
            rgb_composite[:, :, i] = normalize_for_display(image[:, :, i])

        axes[1, 1].imshow(rgb_composite.astype(np.uint8), aspect='auto')
        axes[1, 1].set_title('RGB Composite (R:Refl, G:Range, B:Normal)')
        axes[1, 1].axis('off')

        plt.tight_layout()

    else:
        # Display single channel
        if channel_idx not in [0, 1, 2]:
            raise ValueError(f"Invalid channel index: {channel_idx}. Must be 0, 1, or 2.")

        channel = normalize_for_display(image[:, :, channel_idx])

        plt.figure(figsize=(12, 6))
        plt.imshow(channel, cmap='viridis', aspect='auto')
        plt.title(f'Channel {channel_idx}: {channel_names[channel_idx]}',
                 fontsize=14, fontweight='bold')
        plt.colorbar(fraction=0.046, pad=0.04, label='Intensity (0-255)')
        plt.axis('off')
        plt.tight_layout()

    # Save if requested
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"Saved visualization to: {save_path}")

    # Show if requested
    if show:
        plt.show()
    else:
        plt.close()


def print_image_stats(image):
    """Print statistics about the RIV image."""
    channel_names = ['Reflectivity', 'Range', 'Normal Intensity']

    print("\n" + "="*60)
    print("RIV Image Statistics")
    print("="*60)
    print(f"Shape: {image.shape} (Height x Width x Channels)")
    print(f"Data type: {image.dtype}")
    print()

    for i in range(3):
        channel = image[:, :, i]
        non_zero = channel[channel > 0]

        print(f"Channel {i}: {channel_names[i]}")
        print(f"  Min: {channel.min():.2f}")
        print(f"  Max: {channel.max():.2f}")
        print(f"  Mean: {channel.mean():.2f}")
        print(f"  Std: {channel.std():.2f}")
        if len(non_zero) > 0:
            print(f"  Non-zero pixels: {len(non_zero)} ({100*len(non_zero)/channel.size:.1f}%)")
            print(f"  Non-zero mean: {non_zero.mean():.2f}")
        print()

    print("="*60 + "\n")


def main():
    parser = argparse.ArgumentParser(
        description='Visualize RIV images generated by generate_riv_images.py',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Display all channels
  python visualize_riv_images.py output/000000.npy

  # Display only the range channel (channel 1)
  python visualize_riv_images.py output/000000.npy --channel 1

  # Save visualization without displaying
  python visualize_riv_images.py output/000000.npy --save viz.png --no-show

  # Show statistics only
  python visualize_riv_images.py output/000000.npy --stats-only
        """
    )

    parser.add_argument('npy_file', type=str,
                       help='Path to the .npy file to visualize')
    parser.add_argument('--channel', type=int, choices=[0, 1, 2], default=None,
                       help='Display specific channel (0:Reflectivity, 1:Range, 2:Normal). '
                            'If not specified, shows all channels.')
    parser.add_argument('--save', type=str, default=None,
                       help='Path to save the visualization (e.g., output.png)')
    parser.add_argument('--no-show', action='store_true',
                       help='Do not display the visualization window')
    parser.add_argument('--stats-only', action='store_true',
                       help='Only print statistics without visualization')

    args = parser.parse_args()

    # Load image
    try:
        print(f"Loading RIV image from: {args.npy_file}")
        image = load_riv_image(args.npy_file)
        print(f"Successfully loaded image with shape: {image.shape}")
    except Exception as e:
        print(f"Error loading image: {e}", file=sys.stderr)
        return 1

    # Print statistics
    print_image_stats(image)

    # Visualize unless stats-only
    if not args.stats_only:
        try:
            visualize_channels(
                image,
                channel_idx=args.channel,
                save_path=args.save,
                show=not args.no_show
            )
        except Exception as e:
            print(f"Error during visualization: {e}", file=sys.stderr)
            return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
